'use client'

// AI Morning Briefing card — gold-accented hero shown atop each role dashboard.
// The body text is generated by the health-engine-fed LLM (or a deterministic
// fallback) in lib/briefing.
//   • Refresh  → busts today's cache and re-renders so a fresh briefing is
//                generated on demand (handy for demos).
//   • Send     → sends the current briefing text to the signed-in user's own
//                WhatsApp number (best-effort; only delivers inside the 24h window).
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Sparkles, RefreshCw, Send } from 'lucide-react'
import type { Briefing, BriefingScope } from '@/lib/briefing/facts'

export function BriefingCard({ briefing, scope, scopeId }: { briefing: Briefing; scope: BriefingScope; scopeId: string }) {
  const router = useRouter()
  const [busy, setBusy] = useState(false)
  const [sending, setSending] = useState(false)
  const [status, setStatus] = useState<{ kind: 'ok' | 'err'; msg: string } | null>(null)
  if (!briefing?.body) return null

  async function refresh() {
    if (busy) return
    setBusy(true); setStatus(null)
    try {
      await fetch('/api/briefing/refresh', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scope, scopeId }),
      })
      router.refresh() // re-render server components → regenerate fresh briefing
    } finally {
      setBusy(false)
    }
  }

  async function sendWhatsApp() {
    if (sending) return
    setSending(true); setStatus(null)
    const text = `${briefing.headline ? `*${briefing.headline}*\n\n` : ''}${briefing.body}\n\n— Motiv briefing`
    try {
      const res = await fetch('/api/briefing/whatsapp', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      })
      const d = await res.json().catch(() => ({}))
      setStatus(res.ok ? { kind: 'ok', msg: 'Sent to your WhatsApp ✓' } : { kind: 'err', msg: d.error ?? 'Could not send.' })
    } catch {
      setStatus({ kind: 'err', msg: 'Could not send.' })
    } finally {
      setSending(false)
    }
  }

  return (
    <div className="rounded-2xl bg-[var(--surface)] ring-1 ring-[#C6A35D]/40 p-5">
      <div className="flex items-start gap-4">
        <span className="shrink-0 grid place-items-center w-9 h-9 rounded-xl bg-[#C6A35D]/15 ring-1 ring-[#C6A35D]/30">
          <Sparkles size={18} className="text-[#C6A35D]" />
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 mb-0.5">
            <h2 className="text-sm font-bold text-[var(--text)]">{briefing.headline || 'Your briefing'}</h2>
            <span className="text-[10px] font-semibold uppercase tracking-wide text-[#C6A35D] bg-[#C6A35D]/10 rounded-full px-1.5 py-0.5">
              {briefing.source === 'ai' ? 'AI' : 'Summary'}
            </span>
          </div>
          <p className="text-sm text-[var(--text-muted)] leading-relaxed">{briefing.body}</p>
        </div>
        <div className="flex items-center gap-1 shrink-0">
          <button
            type="button" onClick={sendWhatsApp} disabled={sending} aria-label="Send to my WhatsApp"
            title="Send to my WhatsApp"
            className="-m-1 p-1.5 rounded-lg text-[var(--text-faint)] hover:text-emerald-500 hover:bg-emerald-500/10 transition disabled:opacity-60"
          >
            <Send size={15} className={sending ? 'animate-pulse' : ''} />
          </button>
          <button
            type="button" onClick={refresh} disabled={busy} aria-label="Refresh briefing"
            title="Refresh briefing"
            className="-m-1 p-1.5 rounded-lg text-[var(--text-faint)] hover:text-[#C6A35D] hover:bg-[#C6A35D]/10 transition disabled:opacity-60"
          >
            <RefreshCw size={15} className={busy ? 'animate-spin' : ''} />
          </button>
        </div>
      </div>
      {status && (
        <p className={`mt-2 pl-[3.25rem] text-[11px] ${status.kind === 'ok' ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500'}`}>{status.msg}</p>
      )}
    </div>
  )
}
