// AI Morning Briefing card — gold-accented hero shown atop each role dashboard.
// Presentational + server-safe (no client hooks). The body text is generated by
// the health-engine-fed LLM (or a deterministic fallback) in lib/briefing.
import { Sparkles } from 'lucide-react'
import type { Briefing } from '@/lib/briefing/facts'

export function BriefingCard({ briefing }: { briefing: Briefing }) {
  if (!briefing?.body) return null
  return (
    <div className="rounded-2xl bg-[var(--surface)] ring-1 ring-[#C6A35D]/40 p-5 flex items-start gap-4">
      <span className="shrink-0 grid place-items-center w-9 h-9 rounded-xl bg-[#C6A35D]/15 ring-1 ring-[#C6A35D]/30">
        <Sparkles size={18} className="text-[#C6A35D]" />
      </span>
      <div className="min-w-0">
        <div className="flex items-center gap-2 mb-0.5">
          <h2 className="text-sm font-bold text-[var(--text)]">{briefing.headline || 'Your briefing'}</h2>
          <span className="text-[10px] font-semibold uppercase tracking-wide text-[#C6A35D] bg-[#C6A35D]/10 rounded-full px-1.5 py-0.5">
            {briefing.source === 'ai' ? 'AI' : 'Summary'}
          </span>
        </div>
        <p className="text-sm text-[var(--text-muted)] leading-relaxed">{briefing.body}</p>
      </div>
    </div>
  )
}
